apiVersion: v1
name: istio-ingress-gateway
version: 0.1.0

dependencies:
- name: gateway
  repository: https://istio-release.storage.googleapis.com/charts
  version: 1.20.2
  condition: istioIngressGateway.enabled
