gateway:
  labels:
    istio: ingressgateway
  service:
    # loadBalancerIP: ""
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    externalTrafficPolicy: Local

istioIngressGateway:
  enabled: false
